print("======== DESAFIO 002 ========")
print("Produzido por Álisson Alves")
nome = input("Digite seu nome: ")
print("Meu nome é James Robot - É um prazer te conhecer,",nome+"!")
print(".")
print(".")
print(".")
print(".")
print(".")
print(".")
print("======== FIM DESAFIO 002 ========")