# -*- coding: UTF-8 -*-
print("======== DESAFIO 002 ========")
nome = input("Digite seu nome: ")
print("Meu nome é Robô James - É um prazer te conhecer,",nome+"!")
print(".")
print(".")
print(".")
print(".")
print(".")
print(".")
print("======== FIM DESAFIO 002 ========")